export const QUIZ_POOL = [
  { kapampangan: 'Mangabiran', correct: 'Maging biased', options: ['Maging biased', 'Magalit nang sobra', 'Maging mabilis', 'Maging malungkot'] },
  { kapampangan: 'Salangian', correct: 'Sindihan', options: ['Patayin', 'Sindihan', 'Takbuhan', 'Lutuin'] },
  { kapampangan: 'Alingasngas', correct: 'Eskandalo / Tsismis', options: ['Katahimikan', 'Magandang tanawin', 'Malakas na musika', 'Eskandalo / Tsismis'] },
  { kapampangan: 'Pipumpunan', correct: 'Mga ninuno', options: ['Mga apo', 'Mga ninuno', 'Mga anak', 'Mga kamag-anak'] },
  { kapampangan: 'Maglolo', correct: 'Manligaw', options: ['Manligaw', 'Makipag-away', 'Magsayaw', 'Magluto'] },
  { kapampangan: 'Makabayat', correct: 'Mabigat', options: ['Magaan', 'Mabigat', 'Makulay', 'Masarap'] },
  { kapampangan: 'Makatuknang', correct: 'Nakatira', options: ['Nakatira', 'Nagtatrabaho', 'Naglalaro', 'Natutulog'] },
  { kapampangan: 'Pamangamanu', correct: 'Wika / Salita', options: ['Awit / Kanta', 'Sulat / Liham', 'Wika / Salita', 'Sayaw'] },
  { kapampangan: 'Salapian', correct: 'Mayaman', options: ['Mayaman', 'Mahirap', 'Matamad', 'Matalino'] },
  { kapampangan: 'Katatawanan', correct: 'Katotohanan', options: ['Katotohanan', 'Kasinungalingan', 'Panaginip', 'Biro'] },
  { kapampangan: 'Paglalawen', correct: 'Pinagmamasdan', options: ['Binabalewala', 'Pinagmamasdan', 'Pinakikinggan', 'Inaamoy'] },
  { kapampangan: 'Luid', correct: 'Mabuhay / Kasaganaan', options: ['Paalam', 'Magandang gabi', 'Salamat', 'Mabuhay / Kasaganaan'] },
  { kapampangan: 'Bala-bala', correct: 'Nagkukunwari', options: ['Nagkukunwari', 'Totohanan', 'Galit', 'Seryoso'] },
  { kapampangan: 'Kaluklukan', correct: 'Upuan / Posisyon', options: ['Upuan / Posisyon', 'Higaan', 'Lamesa', 'Pintuan'] },
  { kapampangan: 'Kamalig', correct: 'Bangan / Imbakan', options: ['Bahay', 'Bangan / Imbakan', 'Simbahan', 'Palengke'] },
  { kapampangan: 'Gugulisak', correct: 'Sumisigaw', options: ['Bumubulong', 'Tumatawa', 'Umiiyak', 'Sumisigaw'] },
  { kapampangan: 'Makapangilabut', correct: 'Nakakatakot', options: ['Nakakatawa', 'Nakakabagot', 'Nakakatakot', 'Nakaka-excite'] },
  { kapampangan: 'Sasalikut', correct: 'Nagtatago', options: ['Nagtatago', 'Naghahanap', 'Tumatakbo', 'Tumatalon'] },
  { kapampangan: 'Alipugpug', correct: 'Ipu-ipo', options: ['Ipu-ipo', 'Ulan', 'Lindol', 'Baha'] },
  { kapampangan: 'Papanik', correct: 'Umaakyat', options: ['Umaakyat', 'Bumababa', 'Dumidiretso', 'Lumaliko'] },
  { kapampangan: 'Mamalipit', correct: 'Pumipilipit', options: ['Humihila', 'Nagtutulak', 'Sumisira', 'Pumipilipit'] },
  { kapampangan: 'Salilung', correct: 'Lilim', options: ['Araw', 'Lilim', 'Ulan', 'Hangin'] },
  { kapampangan: 'Taram', correct: 'Talim', options: ['Talim', 'Pupu', 'Dulas', 'Gaspang'] },
  { kapampangan: 'Pipikat', correct: 'Kumukurap', options: ['Kumukurap', 'Tumatitig', 'Pumipikit', 'Lumuha'] },
  { kapampangan: 'Dayat-malat', correct: 'Dagat', options: ['Ilog', 'Lawa', 'Sapa', 'Dagat'] },
  // 25 NEW QUESTIONS
  { kapampangan: 'Tingga', correct: 'Tingi / Titingin', options: ['Tingi / Titingin', 'Hahawak', 'Lalakad', 'Kakain'] },
  { kapampangan: 'Sampaga', correct: 'Bulaklak', options: ['Dahon', 'Puno', 'Bulaklak', 'Bunga'] },
  { kapampangan: 'Balas', correct: 'Buhangin', options: ['Bato', 'Lupa', 'Buhangin', 'Puno'] },
  { kapampangan: 'Batuin', correct: 'Bituin', options: ['Buwan', 'Araw', 'Ulap', 'Bituin'] },
  { kapampangan: 'Buntuk', correct: 'Ulo', options: ['Paa', 'Kamay', 'Tiyan', 'Ulo'] },
  { kapampangan: 'Sibul', correct: 'Bukal ng tubig', options: ['Ulan', 'Bukal ng tubig', 'Dagat', 'Ilog'] },
  { kapampangan: 'Balen', correct: 'Bayan', options: ['Bayan', 'Bansa', 'Lungsod', 'Mundo'] },
  { kapampangan: 'Kapatad', correct: 'Kapatid', options: ['Pinsan', 'Tito', 'Kapatid', 'Kaibigan'] },
  { kapampangan: 'Sulu', correct: 'Ilaw', options: ['Ilaw', 'Apoy', 'Dilim', 'Gabi'] },
  { kapampangan: 'Busal', correct: 'Gitna', options: ['Gilid', 'Gitna', 'Taas', 'Baba'] },
  { kapampangan: 'Alapaap', correct: 'Kaitaasan / Langit', options: ['Lupa', 'Kaitaasan / Langit', 'Ilalim', 'Gubat'] },
  { kapampangan: 'Baling', correct: 'Amoy', options: ['Amoy', 'Lasa', 'Tunog', 'Itsura'] },
  { kapampangan: 'Lauk', correct: 'Halo', options: ['Hiwalay', 'Halo', 'Sama-sama', 'Basag'] },
  { kapampangan: 'Yamut', correct: 'Ugat', options: ['Sangá', 'Dahon', 'Ugat', 'Balat'] },
  { kapampangan: 'Gamat', correct: 'Kamay', options: ['Kamay', 'Paa', 'Binti', 'Braso'] },
  { kapampangan: 'Bitis', correct: 'Paa / Binti', options: ['Paa / Binti', 'Tiyan', 'Ulo', 'Likod'] },
  { kapampangan: 'Kamatayan', correct: 'Kamatayan', options: ['Buhay', 'Kamatayan', 'Sakit', 'Galing'] },
  { kapampangan: 'Pamamasa', correct: 'Pagbasa', options: ['Pagsulat', 'Pagbasa', 'Pagkanta', 'Pagsayaw'] },
  { kapampangan: 'Kasuy', correct: 'Kasoy', options: ['Mani', 'Kasoy', 'Pili', 'Mangga'] },
  { kapampangan: 'Makatapak', correct: 'Nakayapak', options: ['Nakasapatos', 'Nakatali', 'Nakayapak', 'Nakalutang'] },
  { kapampangan: 'Talimhaga', correct: 'Talinghaga', options: ['Talinghaga', 'Kwento', 'Kanta', 'Tula'] },
  { kapampangan: 'Alipan', correct: 'Alipin', options: ['Hari', 'Alipin', 'Kawal', 'Mayaman'] },
  { kapampangan: 'Timawa', correct: 'Malaya', options: ['Malaya', 'Nakulong', 'Alipin', 'Mahirap'] },
  { kapampangan: 'Sagmit', correct: 'Hablot', options: ['Hawak', 'Hablot', 'Bitaw', 'Tapon'] },
  { kapampangan: 'Kasangkapan', correct: 'Gamit / Kagamitan', options: ['Pagkain', 'Damit', 'Gamit / Kagamitan', 'Pera'] }
];

export const getRandomQuestions = (count: number = 5) => {
  const shuffled = [...QUIZ_POOL].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};
