name: Build Android Preview APK
on:
  push:
    branches:
      - master

jobs:
  build_android:
    name: Build Android Preview APK
    type: build
    params:
      platform: android
      profile: preview
